services:
    Mcfedr\QueueManagerBundle\Runner\JobExecutor:
        class: Mcfedr\QueueManagerBundle\Runner\JobExecutor
        calls:
            - ['setContainer', ['@service_container']]

    mcfedr_queue_manager.job_executor:
        alias: Mcfedr\QueueManagerBundle\Runner\JobExecutor
